### ISSUE TITLE
First installation from branch human_addition

### ISSUE THREAD

**Issue by Sebastianaplikacja** [Rolv-Arild/Necto#21]
I install from branch human_addition and after run runDistributedWorker and get error from   rocket_learn:

Traceback (most recent call last):
  File "worker.py", line 14, in <module>
    from rocket_learn.rollout_generator.redis_rollout_generator import RedisRolloutWorker, _unserialize
ModuleNotFoundError: No module named 'rocket_learn.rollout_generator.redis_rollout_generator'

What version of what branch need to be rocket_learn install? to be this work after install. After that is couple more errors like tuples from rocket_learn and etc that crashes when match start.

Rocket_learn i install from that line
python -m pip install -U git+https://github.com/Rolv-Arild/rocket-learn.git

**Comment by DanielDowns** [comment]
We aren't accepting any more compute at this time.
