### ISSUE TITLE
 password and ip for Necto traning

### ISSUE THREAD

**Issue by Sebastianaplikacja** [Rolv-Arild/Necto#22]
To start computing
clone repo
start cmd as admin
create symlink to repo\training\training repo\training (mklink /D path\to\repo\training\training path\to\repo\training)
close cmd
open repo\training in windows explorer or non-admin cmd
Run runDistributedWorker.bat
enter your name + server ip + server password
when asked for the IP and password, dm Soren and he'll fill you in.

Can i get password and ip or copy of redis database @DanielDowns?

**Comment by DanielDowns** [comment]
Thanks for the offer, but Nexto is done training. We aren't accepting any more compute.
