### ISSUE TITLE
Errors while running with RLBot (could not broadcast input array...)

### ISSUE THREAD

**Issue by mgavin** [Rolv-Arild/Necto#6]
- Installed RLBot today [ 2 / 16 / 2022 ]
- Installed the default python version they recommended [ 3.7.9 ]
- Installed required packages for Necto through the RLBotGUI
- (noticed I needed node) Installed node from nodejs.org
- Tried adding the bot to a 2v1 match; bots don't properly run... there are errors in the RLBot debug window

Traceback:

![image](https://user-images.githubusercontent.com/1364492/154373145-9c291371-e176-4f88-ad35-90275b873583.png)

**Comment by DanielDowns** [comment]
I just double checked and I can successfully run a 2v1, both as Blue and Orange. Is there anything else about your game that's different? Playing over LAN, observers, etc?

**Comment by mgavin** [comment]
So it seems the size of `BOOST_LOCATIONS` is (34, 3) while `qkv[0, n:, 5:8]` is  (35, 3). So I just added another element, duplicating the last line of BOOST_LOCATIONS, and that satisfies it.

I started rocket league through the RLBot GUI and I have bakkesmod installed as well, although I wouldn't think it would affect the issue here.. or perhaps bakkesmod is affecting the number of players? Since I haven't decoded what qkv[0, n:, 5:8] refers to. 

Okay, trying...

**Comment by DanielDowns** [comment]
It might. Try disabling it for the time being.

**Comment by mgavin** [comment]
I quit out bakkesmod, RLBot, closed everything... re-ran RLBotGUI, have myself on team blue, 2 Nectos on team orange, have one mutator set for unlimited match length, Extra set to only Enable State Setting and Skip Replays, ... and still get the error in the debug log

**Comment by DanielDowns** [comment]
What map are you using? Try DFHStadium.

**Comment by mgavin** [comment]
I was on BeckwithPart_Midnight, and you're right, going to DFHStadium fixes the issue :)
